name: Cereal Mac CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test_cereal_macos:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - CMAKE_OPTIONS: '-DWITH_WERROR=OFF -DSKIP_PORTABILITY_TEST=ON -DSKIP_PERFORMANCE_COMPARISON=ON'
            COMPILER: 'clang++'
            NAME: macos-latest-clang-xcode-latest

    name: ${{ matrix.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build and test
        shell: bash
        env:
          CMAKE_OPTIONS: ${{ matrix.CMAKE_OPTIONS }}
          COMPILER: ${{ matrix.COMPILER }}
        run: |
          set -ex
          
          # Set compiler and env variables
          export CXX=${COMPILER}
          ${CXX} --version

          # Build cereal and test
          cmake --version
          mkdir build && cd build
          cmake ${CMAKE_OPTIONS} .. && make -j4 VERBOSE=1
          ctest . --output-on-failure
